/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class basics_jni_java_JNI */

#ifndef _Included_basics_jni_java_JNI
#define _Included_basics_jni_java_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     basics_jni_java_JNI
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_basics_jni_java_JNI_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
