/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_batchsight_demo_test_JNI */

#ifndef _Included_com_batchsight_demo_test_JNI
#define _Included_com_batchsight_demo_test_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_batchsight_demo_test_JNI
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_batchsight_demo_test_JNI_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
