/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class machine_JniCall */

#ifndef _Included_machine_JniCall
#define _Included_machine_JniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     machine_JniCall
 * Method:    sayBaBi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_machine_JniCall_sayBaBi
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
